"""Build an external-object-list to scannable-scene map from NMS assets."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import runpy
import xml.etree.ElementTree as ET


ANALYSIS_ROOT = Path(os.environ["LOCALAPPDATA"]) / "NMSDiscoveryLab" / "analysis"
BIOME_ROOT = ANALYSIS_ROOT / "stage9_all_biomes"
PROJECT_ROOT = Path(__file__).parents[1]
GENERATED_TYPES = runpy.run_path(PROJECT_ROOT / "src" / "planet_object_types.py")
SCENE_TYPES = {
    **{value: 4 for value in GENERATED_TYPES["FLORA_SCENE_HASHES"]},
    **{value: 5 for value in GENERATED_TYPES["MINERAL_SCENE_HASHES"]},
}
UINT64_MASK = 0xFFFFFFFFFFFFFFFF


def _original_path(filename: Path, root: Path) -> str:
    relative = filename.relative_to(root).as_posix().upper()
    if not relative.endswith(".MXML"):
        raise ValueError(f"unexpected analysis filename: {filename}")
    return f"{relative[:-5]}.MBIN"


def _djb2_64(value: str) -> int:
    result = 0x1505
    for byte in value.encode("ascii"):
        result = (result * 0x21 + byte) & UINT64_MASK
    return result


def build_object_lists() -> dict[int, tuple[int, ...]]:
    result: dict[int, tuple[int, ...]] = {}
    for filename in BIOME_ROOT.rglob("*.MXML"):
        tree = ET.parse(filename)
        root = tree.getroot()
        if root.get("template") != "cGcExternalObjectList":
            continue
        scene_hashes: set[int] = set()
        for element in root.iter("Property"):
            if element.get("name") != "Filename":
                continue
            value = element.get("value", "").replace("\\", "/").upper()
            if not value.endswith(".SCENE.MBIN"):
                continue
            scene_hash = _djb2_64(value)
            if scene_hash in SCENE_TYPES:
                scene_hashes.add(scene_hash)
        list_hash = _djb2_64(_original_path(filename, BIOME_ROOT))
        result[list_hash] = tuple(sorted(scene_hashes))
    return result


def render_python_module(object_lists: dict[int, tuple[int, ...]]) -> str:
    lines = [
        '"""Generated NMS 7.0 external object-list scene membership.',
        "",
        "Generated by analysis/build_stage9_object_list_map.py from game assets.",
        'Do not edit this file by hand.',
        '"""',
        "",
        "OBJECT_LIST_SCENE_HASHES = {",
    ]
    for list_hash, scene_hashes in sorted(object_lists.items()):
        values = ", ".join(f"0x{value:016X}" for value in scene_hashes)
        if len(scene_hashes) == 1:
            values += ","
        lines.append(f"    0x{list_hash:016X}: ({values}),")
    lines.extend(("}", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    object_lists = build_object_lists()
    nonempty = sum(bool(values) for values in object_lists.values())
    memberships = sum(len(values) for values in object_lists.values())
    print(
        f"object_lists={len(object_lists)} nonempty={nonempty} "
        f"memberships={memberships}"
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(render_python_module(object_lists), encoding="utf-8")
        print(f"wrote={args.output}")


if __name__ == "__main__":
    main()
