"""Build a static scene-path to discovery-type map from extracted NMS assets."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import xml.etree.ElementTree as ET


ANALYSIS_ROOT = Path(os.environ["LOCALAPPDATA"]) / "NMSDiscoveryLab" / "analysis"
SCENE_ROOT = ANALYSIS_ROOT / "stage9_all_scenes"
ENTITY_ROOT = ANALYSIS_ROOT / "stage9_all_entities"
UINT64_MASK = 0xFFFFFFFFFFFFFFFF

# Runtime evidence from build 178938 that overrides the static attachment rule.
# - STEAMVENT is typed only through the ScanIcon of its child GEM entity; the
#   Discoveries page never counts it, so it must not be submitted.
# - FISHFIENDROCK attaches no entity directly (its FIENDROCKNEST sub-scene is not
#   extracted), but the game's own resolver reports it as Mineral and it is part
#   of the Discoveries mineral denominator.
SCENE_TYPE_OVERRIDES: dict[str, str | None] = {
    "MODELS/PLANETS/BIOMES/UNDERWATER/INTERACTIVE/STEAMVENT.SCENE.MBIN": None,
    "MODELS/PLANETS/BIOMES/UNDERWATER/INTERACTIVE/FISHFIENDROCK.SCENE.MBIN": "Mineral",
}


def _original_path(filename: Path, root: Path) -> str:
    relative = filename.relative_to(root).as_posix().upper()
    if not relative.endswith(".MXML"):
        raise ValueError(f"unexpected analysis filename: {filename}")
    return f"{relative[:-5]}.MBIN"


def _djb2_64(value: str) -> int:
    result = 0x1505
    for byte in value.encode("ascii"):
        result = (result * 0x21 + byte) & UINT64_MASK
    return result


def build_scene_types() -> dict[str, str]:
    entity_types: dict[str, str] = {}
    for filename in ENTITY_ROOT.rglob("*.ENTITY.MXML"):
        values = {
            element.get("value", "")
            for element in ET.parse(filename).iter("Property")
            if element.get("name") == "DiscoveryType"
            and element.get("value") in {"Flora", "Mineral"}
        }
        if len(values) == 1:
            entity_types[_original_path(filename, ENTITY_ROOT)] = values.pop()

    scene_types: dict[str, str] = {}
    for filename in SCENE_ROOT.rglob("*.SCENE.MXML"):
        attachment_types: set[str] = set()
        for element in ET.parse(filename).iter("Property"):
            if element.get("name") != "Value":
                continue
            value = element.get("value", "").replace("\\", "/").upper()
            if value.endswith(".ENTITY.MBIN") and value in entity_types:
                attachment_types.add(entity_types[value])
        if len(attachment_types) == 1:
            scene_types[_original_path(filename, SCENE_ROOT)] = attachment_types.pop()
    for path, discovery_type in SCENE_TYPE_OVERRIDES.items():
        if discovery_type is None:
            scene_types.pop(path, None)
        else:
            scene_types[path] = discovery_type
    return scene_types


def render_python_module(scene_types: dict[str, str]) -> str:
    hash_types: dict[int, str] = {}
    for path, discovery_type in scene_types.items():
        scene_hash = _djb2_64(path)
        previous = hash_types.setdefault(scene_hash, discovery_type)
        if previous != discovery_type:
            raise ValueError(
                f"scene hash collision: 0x{scene_hash:016X} is both "
                f"{previous} and {discovery_type}"
            )

    lines = [
        '"""Generated NMS 7.0 scannable object scene hashes.',
        "",
        "Generated by analysis/build_stage9_scene_types.py from game MBIN assets.",
        'Do not edit this file by hand.',
        '"""',
        "",
    ]
    for discovery_type, constant in (
        ("Flora", "FLORA_SCENE_HASHES"),
        ("Mineral", "MINERAL_SCENE_HASHES"),
    ):
        hashes = sorted(
            scene_hash
            for scene_hash, value in hash_types.items()
            if value == discovery_type
        )
        lines.append(f"{constant} = frozenset((")
        lines.extend(f"    0x{scene_hash:016X}," for scene_hash in hashes)
        lines.append("))")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    scene_types = build_scene_types()
    counts = {
        discovery_type: sum(value == discovery_type for value in scene_types.values())
        for discovery_type in ("Flora", "Mineral")
    }
    print(f"scene_types={len(scene_types)} counts={counts}")
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(render_python_module(scene_types), encoding="utf-8")
        print(f"wrote={args.output}")
        return
    for path, discovery_type in sorted(scene_types.items()):
        print(f"{discovery_type}|{_djb2_64(path):016X}|{path}")


if __name__ == "__main__":
    main()
